"""
Second-stage FLUX diagnostic: bypasses our entire guidance module and feeds
the cached T5 + CLIP embeddings directly into the off-the-shelf FluxPipeline
to generate a reference image from pure noise.

Use this AFTER `diagnose_flux_guidance.py` if the target images look like
noise/grid. The two outcomes tell you exactly where the bug is:

  (1) `pipeline_from_cache.png` LOOKS LIKE THE PROMPT
      -> the cached embeddings are correct. The bug is in our guidance module
         (transformer call args, packing, sigma feeding, inversion math).

  (2) `pipeline_from_cache.png` IS NOISE / GRID / GRAY
      -> the cached embeddings are wrong. Inspect the encoder code in
         `flux_prompt_processor.py`'s `spawn_func` (pooler_output extraction,
         T5 last_hidden_state[0], dtype/device handoff to cache).

A third sanity image `pipeline_freshencode.png` is generated by FluxPipeline
encoding the same prompt itself (no cache); compare the two to see whether
caching round-trip is the culprit.

Usage:
    python scripts/diagnose_flux_cache.py
    python scripts/diagnose_flux_cache.py --prompt "a DSLR photo of a red apple on a wooden table"
"""
import argparse
import os
import sys
from pathlib import Path

import torch
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def _stats(name: str, t: torch.Tensor):
    t = t.detach().float().cpu()
    norm_per_token = t.flatten(start_dim=-1).norm(dim=-1)
    print(
        f"  [{name}] shape={tuple(t.shape)} dtype={t.dtype}  "
        f"mean={t.mean().item(): .4f}  std={t.std().item(): .4f}  "
        f"abs_max={t.abs().max().item(): .4f}  "
        f"token_norm: min={norm_per_token.min().item(): .3f} "
        f"max={norm_per_token.max().item(): .3f}"
    )


def load_cached_embeddings(model: str, prompt: str, cache_dir: str):
    """Load the cached {prompt_emb, pooled_emb} dict for `prompt`."""
    from threestudio.models.prompt_processors.base import hash_prompt

    path = os.path.join(cache_dir, f"{hash_prompt(model, prompt)}.pt")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"No cached embedding at {path} -- run flux_prompt_processor first "
            f"(or `scripts/diagnose_flux_guidance.py`) to populate the cache."
        )
    print(f"[cache] Loading {path}")
    d = torch.load(path, map_location="cpu")
    return d["prompt_emb"], d["pooled_emb"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prompt", default="a DSLR photo of a red apple on a wooden table")
    ap.add_argument(
        "--cached-prompt",
        default=None,
        help="Prompt key for the cache lookup (defaults to '<prompt>, side view' "
             "to match flux_prompt_processor's view-dependent expansion).",
    )
    ap.add_argument("--model", default="black-forest-labs/FLUX.1-dev")
    ap.add_argument(
        "--cache-dir",
        default=".threestudio_cache/flux_embeddings",
    )
    ap.add_argument("--out", default="results/flux_diagnose")
    ap.add_argument("--guidance-scale", type=float, default=3.5)
    ap.add_argument("--n-steps", type=int, default=20)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--height", type=int, default=512)
    ap.add_argument("--width", type=int, default=512)
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)

    cached_prompt = args.cached_prompt or f"{args.prompt}, side view"
    print(f"[cfg] generation prompt = {args.prompt!r}")
    print(f"[cfg] cache lookup key  = {cached_prompt!r}")

    # ---- 1) Load cached embeddings (what our guidance feeds the transformer).
    prompt_emb, pooled_emb = load_cached_embeddings(
        args.model, cached_prompt, args.cache_dir
    )
    print("[cache] embedding stats:")
    _stats("prompt_emb (T5)", prompt_emb)
    _stats("pooled_emb (CLIP)", pooled_emb)

    # ---- 2) Build FluxPipeline (with text encoders intact, since we want a
    #         fresh-encode reference too).
    print("[pipeline] Loading FluxPipeline (this may take ~60s)...")
    from diffusers import FluxPipeline

    pipe = FluxPipeline.from_pretrained(args.model, torch_dtype=torch.bfloat16)
    pipe = pipe.to("cuda")

    # ---- 3) Generate from CACHED embeddings (skips text encoders entirely).
    print("[run1] Generating from CACHED embeddings (no text encoders used)...")
    gen = torch.Generator(device="cuda").manual_seed(args.seed)
    img_cache = pipe(
        prompt_embeds=prompt_emb.to("cuda", torch.bfloat16).unsqueeze(0),
        pooled_prompt_embeds=pooled_emb.to("cuda", torch.bfloat16).unsqueeze(0),
        num_inference_steps=args.n_steps,
        guidance_scale=args.guidance_scale,
        height=args.height,
        width=args.width,
        generator=gen,
    ).images[0]
    cache_path = os.path.join(args.out, "pipeline_from_cache.png")
    img_cache.save(cache_path)
    print(f"  -> {cache_path}")

    # ---- 4) Compute fresh embeddings via the pipeline and compare numerically.
    print("[run2] Re-encoding prompt via FluxPipeline (fresh)...")
    fresh_t5, fresh_pooled, _ = pipe.encode_prompt(
        prompt=cached_prompt,
        prompt_2=cached_prompt,
        max_sequence_length=prompt_emb.shape[0],
        device="cuda",
    )
    fresh_t5 = fresh_t5[0].detach().float().cpu()  # (L, 4096)
    fresh_pooled = fresh_pooled[0].detach().float().cpu()  # (768,)
    print("[fresh] embedding stats:")
    _stats("prompt_emb (T5) fresh", fresh_t5)
    _stats("pooled_emb (CLIP) fresh", fresh_pooled)

    def _diff(name, a, b):
        a, b = a.detach().float().cpu(), b.detach().float().cpu()
        if a.shape != b.shape:
            print(f"  [{name}] shape mismatch: cached={tuple(a.shape)} fresh={tuple(b.shape)}")
            return
        absdiff = (a - b).abs()
        cos = torch.nn.functional.cosine_similarity(
            a.flatten().unsqueeze(0), b.flatten().unsqueeze(0)
        ).item()
        print(
            f"  [{name}] abs_diff mean={absdiff.mean().item():.4e} "
            f"max={absdiff.max().item():.4e}  cos_sim={cos:.4f}"
        )

    print("[diff] cached vs fresh:")
    _diff("prompt_emb (T5)", prompt_emb, fresh_t5)
    _diff("pooled_emb (CLIP)", pooled_emb, fresh_pooled)

    # ---- 5) Generate from FRESHLY encoded embeddings as a baseline reference.
    print("[run3] Generating from FRESH (just-encoded) embeddings...")
    gen = torch.Generator(device="cuda").manual_seed(args.seed)
    img_fresh = pipe(
        prompt_embeds=fresh_t5.to("cuda", torch.bfloat16).unsqueeze(0),
        pooled_prompt_embeds=fresh_pooled.to("cuda", torch.bfloat16).unsqueeze(0),
        num_inference_steps=args.n_steps,
        guidance_scale=args.guidance_scale,
        height=args.height,
        width=args.width,
        generator=gen,
    ).images[0]
    fresh_path = os.path.join(args.out, "pipeline_freshencode.png")
    img_fresh.save(fresh_path)
    print(f"  -> {fresh_path}")

    print()
    print("=" * 64)
    print("Interpretation:")
    print("  pipeline_from_cache.png  -- generated using OUR cached embeddings")
    print("  pipeline_freshencode.png -- generated using pipeline's own encoding")
    print()
    print("  Both look like the prompt -> cache is OK, bug is in guidance module")
    print("  Only fresh works          -> cache is corrupting embeddings")
    print("  Neither works             -> base model / pipeline / env issue")
    print("=" * 64)


if __name__ == "__main__":
    main()
